# Generated by Django 5.1.1 on 2024-10-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphosp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signUp',
            new_name='newmember',
        ),
    ]
