# Generated by Django 5.1.1 on 2024-10-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosp', '0002_rename_signup_newmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('additional_comments', models.CharField(max_length=400)),
            ],
        ),
    ]
