# Generated by Django 5.1.1 on 2024-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosp', '0003_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default='not specified', max_length=25),
        ),
    ]
