# Generated by Django 5.1.1 on 2024-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosp', '0004_appointments_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='payment',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
