# Generated by Django 5.1.1 on 2024-11-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosp', '0007_appointments_bk_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('docId', models.CharField(max_length=200)),
                ('photoDoc', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
