# Generated by Django 5.1.1 on 2024-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosp', '0008_doctoradd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoradd',
            name='photoDoc',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
